### PR TITLE
Update constant.js

### PR DESCRIPTION
**Pull request by notrealregen**
Added Fantom Opera Network configuration to the file.

### CODE REVIEW

**Comment by caffeinum** [comment]
@notrealregen nice! did you try on your website with the new build?

```html
<script>
   CONTRACT_ADDRESS = "<your contract address here>"
   NETWORK_ID = 250
   MAX_PER_MINT = 20
</script>
<script src="https://nftcomponents-git-fork-notrealregen-patch-2-buildship.vercel.app//static/js/main.js"></script>
<link href="https://nftcomponents-git-fork-notrealregen-patch-2-buildship.vercel.app//static/css/main.css" rel="stylesheet">
```

**Comment by theshadowagent** [comment]
@notrealregen did you end up minting successfully on Fantom with this patch?

**Review by caffeinum — CHANGES_REQUESTED** [review]
please rebase the current `main`, we broke the PR by force-pushing

**Comment by caffeinum** [comment]
Please re-open this in correct branch

**Pull request closed without merging**
